name: Deploy Backend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Hostinger via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Definimos la ruta donde está Node, NPM y PM2 según tu servidor
            export PATH=$PATH:/root/.nvm/versions/node/v25.2.1/bin
            
            cd ~/inmobiliaria_backend
            git pull origin main
            
            # Instalación y compilación
            npm install
            npm run build
            
            # Reiniciamos la app usando el nombre exacto que vimos en tu PM2
            pm2 restart inmo-backend || pm2 start dist/main.js --name inmo-backend